# Generated by Django 2.2.9 on 2020-01-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='image',
            new_name='image_landscape',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='image',
            new_name='image_landscape',
        ),
        migrations.AddField(
            model_name='project',
            name='image_portrait',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='section',
            name='image_portrait',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
