# Generated by Django 2.2.9 on 2020-01-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_project_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='title',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
