# Generated by Django 2.2.9 on 2020-01-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_project_exclude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='exclude',
            field=models.BooleanField(default=False),
        ),
    ]
