# Generated by Django 2.2.9 on 2020-01-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20200116_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image_landscape',
            field=models.ImageField(blank=True, upload_to='project_images'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_portrait',
            field=models.ImageField(blank=True, upload_to='project_images'),
        ),
        migrations.AlterField(
            model_name='section',
            name='image_landscape',
            field=models.ImageField(blank=True, upload_to='project_images'),
        ),
        migrations.AlterField(
            model_name='section',
            name='image_portrait',
            field=models.ImageField(blank=True, upload_to='project_images'),
        ),
    ]
