# Generated by Django 2.2.9 on 2020-01-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20200122_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image_landscape',
            field=models.ImageField(default='project_landscape_default.jpg', upload_to='project_images'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_portrait',
            field=models.ImageField(default='project_portrait_default.jpg', upload_to='project_images'),
        ),
    ]
