# Generated by Django 2.2.9 on 2020-01-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_auto_20200122_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='caption',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='section',
            name='caption_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='section',
            name='image',
            field=models.ImageField(blank=True, upload_to='project_images'),
        ),
    ]
