# Generated by Django 2.2.9 on 2020-02-04 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_auto_20200129_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='image_landscape',
        ),
        migrations.RemoveField(
            model_name='section',
            name='image_portrait',
        ),
    ]
