# Generated by Django 2.2.9 on 2020-02-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_auto_20200204_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='home',
            field=models.BooleanField(default=False),
        ),
    ]
