# Generated by Django 2.2.9 on 2020-02-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_project_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pdf_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
