# Generated by Django 2.2.9 on 2020-02-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_auto_20200204_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='exclude',
            field=models.BooleanField(default=False),
        ),
    ]
