# Generated by Django 2.2.9 on 2020-02-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='exclude',
            field=models.BooleanField(default=False),
        ),
    ]
