# Generated by Django 2.2.9 on 2020-02-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20200212_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='category',
            field=models.CharField(choices=[('Architecture', 'Architecture'), ('Graphics', 'Graphics'), ('Interior Design', 'Interior Design'), ('General', 'General')], max_length=20),
        ),
    ]
