# Generated by Django 2.2.9 on 2020-01-10 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200110_1621'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bullet',
        ),
    ]
