# Generated by Django 2.2.9 on 2020-01-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_delete_bullet'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
