# Generated by Django 2.2.9 on 2020-01-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_blog_exclude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='exclude',
            field=models.BooleanField(default=False),
        ),
    ]
