# Generated by Django 2.2.9 on 2020-01-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20200117_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
