# Generated by Django 2.2.9 on 2020-01-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20200117_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='caption',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='blog',
            name='caption_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='section',
            name='caption',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='section',
            name='caption_url',
            field=models.URLField(blank=True),
        ),
    ]
