# Generated by Django 2.2.9 on 2020-02-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_remove_comment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='home',
            field=models.BooleanField(default=False),
        ),
    ]
