# Generated by Django 2.2.9 on 2020-02-04 20:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20200204_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
