# Generated by Django 2.2.9 on 2020-02-12 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20200206_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='home',
        ),
    ]
