# Generated by Django 2.2.9 on 2020-01-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
