# Generated by Django 2.2.9 on 2020-01-27 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_auto_20200127_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_examples', to='portfolio.Project'),
        ),
    ]
