# Generated by Django 2.2.9 on 2020-01-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0006_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='employment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
