# Generated by Django 2.2.9 on 2020-01-29 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0007_auto_20200129_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='employment',
            new_name='job',
        ),
    ]
