# Generated by Django 2.2.9 on 2020-02-10 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0009_contact_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
