# Generated by Django 2.2.9 on 2020-02-06 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='downloads',
            field=models.ManyToManyField(blank=True, to='portfolio.Download'),
        ),
    ]
