# Generated by Django 2.2.9 on 2020-02-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_cart_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='stripe',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
